[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'

per-file-ignores = [
    "__init__.py:F401", # Module imported but unused
]

extend-ignore = [
    "E203", # Whitespace before ":"
    "A002", "A003" # Shadowing python builtin
]
